### ISSUE TITLE
Generally: Async Error Handling

### ISSUE THREAD

**Issue by tsterker** [GLEIF-IT/sally#7]
Imagine
- KARA successfully processes a credential presentation + triggers webhook
- Backend successful responds to webhook
- 2 Hours (weeks, ..) later the backend runs into issues with the payload from the webhook

➡️  How to we remediate such things? There should be some channel to the QVIs for this?

**Comment by pfeairheller** [comment]
QVIs will receive an ACK message after Sally gets a success back from the reporting API web hook so it looks like we are covered here as well.
