### ISSUE TITLE
Sally: Sentry Integration?

### ISSUE THREAD

**Issue by tsterker** [GLEIF-IT/sally#8]
I understand that Sally will be a custom piece of software wrapping `keripy`.
In this case, I'd like to add [Sentry](https://docs.sentry.io/) alerting, which we could leverage for:

- Unexpected exceptions
- Explicit alerts for too many failed webhook attempts (see [webhook retry mechanism](https://github.com/GLEIF-IT/sally/issues/5#issuecomment-1212363959)) and/or unexpected response codes
- Explicit alerts in case of failed (asyc) credential verification
- ...

@pfeairheller @m00sey any opinion on this?

**Comment by pfeairheller** [comment]
As Sentry integration was not part of the original scope, we will not be including it as part of the initial deliverable.  This can be assigned later when we additional work is scheduled for the vLEI.

**Comment by tsterker** [comment]
Superseded by backlog ticket in GLEIF GitLab: https://gitlab.gleif.org/gleif/it/devs/tasks/-/issues/307
